name: deploying Hexo project to aliyun ftp
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0 # 使用专门部署 Hexo 到 FTP 的 action
	with:
          server: ${{ secrets.FTP_SERVER }} # secret 名
          username: ${{ secrets.FTP_USERNAME }} # 公共仓库，格式：GitHub 用户名/仓库名
          password: ${{ secrets.FTP_PASSWORD }} # 分支，填 gh-pages 就行
          local-dir: / # 部署 public 目录下的文件
	  server-dir: ./htdocs/
