- name: FTP Deployment
  # You may pin to the exact commit or the version.
  # uses: airvzxf/ftp-deployment-action@9efe025c218094bd451a0cb684d7cb471f4d9d4f
  uses: airvzxf/ftp-deployment-action@latest
  with:
    # FTP Server.
    server: ${{ secrets.FTP_SERVER }}
    # FTP User.
    user:  ${{ secrets.FTP_USERNAME }}
    # FTP Password.
    password: ${{ secrets.FTP_PASSWORD }}
    # Local directory.
    # Remote directory.
    remote_dir: ./htdocs/
    
